GITHUB_USER="eugene-auduchinok"
REPO_NAME="homework"
REPO_PATH="https://github.com/$GITHUB_USER/$REPO_NAME.git"
SOLUTION_PATH="$REPO_NAME/x71/term3/CSharp/Geometry/Geometry.sln"
LOG_MAIL="fake_address@gmail.com"