GITHUB_USER="eugene-auduchinok"
REPO_NAME="icreated-ios"
REPO_PATH="https://github.com/$GITHUB_USER/$REPO_NAME.git"
APP_NAME="icreated"
WORKSPACE_PATH="$REPO_NAME/$APP_NAME/$APP_NAME.xcworkspace"
LOG_MAIL="eugene.auduchinok@gmail.com"